### ISSUE TITLE
Pretrained models release date

### ISSUE THREAD

**Issue by ZiYang-xie** [NVlabs/EmerNeRF#2]
Thanks for the great work !!!
I'm wondering when the pretrained models will be available?

**Comment by Jiawei-Yang** [comment]
Hi Ziyang, we're likely to release the models after the cvpr deadline : )

**Comment by ZiYang-xie** [comment]
Sounds great! Thanks for letting me know

**Comment by Mayakshamanjirinesht** [comment]
Thanks for this amazing work. When can we expect the pretrained models available for the use? what is the procedure to request it?
