### ISSUE TITLE
Question about coordinate.

### ISSUE THREAD

**Issue by shanxiaojun** [NVlabs/EmerNeRF#3]
Thanks for your great work. I just wonder if you use the same coordinate as LLFF.

**Comment by Jiawei-Yang** [comment]
Hi Shanxiao,

We use the OpenCV coordinate system for camera images. I'm not sure if LLFF uses this one or if it uses the OpenGL coordinate system.

**Comment by shanxiaojun** [comment]
Thank you for your reply!
