### ISSUE TITLE
Question about Downloading Specific Scenes from Waymo Open Dataset

### ISSUE THREAD

**Issue by LZL-CS** [NVlabs/EmerNeRF#6]
Hi, thanks for your excellent work. when I tried to download  Specific Scenes from the Waymo Open Dataset as your instruction, I couldn't find the Waymo data "waymo_open_dataset_scene_flow/train":
https://github.com/NVlabs/EmerNeRF/blob/47f921fe6d34385e441e7f69ed3fd8e9b04b8fad/datasets/download_waymo.py#L31

**Comment by Jiawei-Yang** [comment]
Hi there,

Thanks for your interest in our work. I wonder if you have successfully registered here: https://waymo.com/open/download/
Please make sure you have your account signed in before downloading the data.

**Comment by LZL-CS** [comment]
> Hi there,
> 
> Thanks for your interest in our work. I wonder if you have successfully registered here: https://waymo.com/open/download/ Please make sure you have your account signed in before downloading the data.

Hi @Jiawei-Yang,
I have  successfully registered the Waymo dataset:
<img width="1419" alt="image" src="https://github.com/NVlabs/EmerNeRF/assets/54640259/786bde36-6af5-4245-83a9-af413761cf90">
 May I know which dataset above in Waymo are you using in the paper? Thanks!

**Comment by Jiawei-Yang** [comment]
Hi @LZL-CS 

We're using this split: https://console.cloud.google.com/storage/browser/waymo_open_dataset_scene_flow
which has scene flow labels available.

Best,
Jiawei

**Comment by LZL-CS** [comment]
> Hi @LZL-CS
> 
> We're using this split: https://console.cloud.google.com/storage/browser/waymo_open_dataset_scene_flow which has scene flow labels available.
> 
> Best, Jiawei

Good, I'll try it, and thanks for your prompt reply!
