### ISSUE TITLE
Inquiry About Training on NVIDIA 3090 - Compatibility and Support

### ISSUE THREAD

**Issue by RuihanLu** [NVlabs/EmerNeRF#9]
Hi Jiawei,

First and foremost, I'd like to express my admiration for the incredible work you've done with EmerNeRF. 

I am reaching out with a query regarding training the model on an NVIDIA 3090 GPU. While attempting to train the model, I encountered several issues, particularly when all features were enabled. The system suggests that training requires an A100 GPU, which I currently do not have access to. Below are the specific error messages received:
```
- `cutlassF` is not supported because:
  - xFormers wasn't built with CUDA support
  - Operator wasn't built - see `python -m xformers.info` for more info

- `flshattF` is not supported because:
  - xFormers wasn't built with CUDA support
  - dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
  - Operator wasn't built - see `python -m xformers.info` for more info

- `tritonflashattF` is not supported because:
  - xFormers wasn't built with CUDA support
  - dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
  - Requires A100 GPU

- `smallkF` is not supported because:
  - xFormers wasn't built with CUDA support
  - max(query.shape[-1] != value.shape[-1]) > 32
  - Operator wasn't built - see `python -m xformers.info` for more info
  - Unsupported embed per head: 64
```
I am wondering if it's possible to train this model on a single NVIDIA 3090 GPU and if so, what steps I should take to resolve these issues. I am also particularly interested in any pre-trained models. Do you have a plan to release them?

Any guidance or suggestions would be immensely appreciated.

Thank you for your time and for the groundbreaking work you are doing.

Best regards,
Ruihan

**Comment by Jiawei-Yang** [comment]
Hi Ruihan,

Thanks for your interest in our work! Our current codebase is compatible with NVIDIA 3090 GPU. Have you tried to re-install the `xformers` package as suggested? From what I can tell from the error messages, re-installing `tiny-cuda-nn` and `xFormers` might address your issue.

**Comment by RuihanLu** [comment]
Hi Jiawei,

Thanks a lot! That works good for me.

Best,
Ruihan
